documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'

github_actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/**

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - pyproject.toml
