from typing import Any

OPTIMIZER_RECIPES: list[tuple[str, dict[str, Any], int]] = [
    ('lookahead', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('orthograd', {'lr': 5e-1, 'weight_decay': 1e-3}, 10),
    ('schedulefree', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('adabelief', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('adabelief', {'lr': 5e-1, 'weight_decay': 1e-3, 'ams_bound': True}, 5),
    ('adabelief', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('adabelief', {'lr': 5e-1, 'weight_decay': 1e-3, 'fixed_decay': True}, 5),
    ('adabelief', {'lr': 5e-1, 'weight_decay': 1e-3, 'rectify': True}, 10),
    ('adabound', {'lr': 1e0, 'gamma': 0.1, 'weight_decay': 1e-3}, 20),
    ('adabound', {'lr': 1e0, 'gamma': 0.1, 'weight_decay': 1e-3, 'fixed_decay': True}, 20),
    ('adabound', {'lr': 1e0, 'gamma': 0.1, 'weight_decay': 1e-3, 'weight_decouple': False}, 20),
    ('adabound', {'lr': 1e0, 'gamma': 0.1, 'weight_decay': 1e-3, 'ams_bound': True}, 20),
    ('adai', {'lr': 5e0, 'weight_decay': 0.0, 'use_gc': True}, 5),
    ('adai', {'lr': 5e-1, 'weight_decay': 0.0, 'dampening': 0.9}, 5),
    ('adai', {'lr': 5e-1, 'weight_decay': 1e-4, 'weight_decouple': False}, 5),
    ('adai', {'lr': 5e-1, 'weight_decay': 1e-4, 'weight_decouple': True}, 5),
    ('adai', {'lr': 5e-1, 'weight_decay': 1e-4, 'weight_decouple': False, 'stable_weight_decay': True}, 5),
    ('adai', {'lr': 5e-1, 'weight_decay': 1e-4, 'weight_decouple': True, 'stable_weight_decay': True}, 5),
    ('adamp', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('adamp', {'lr': 5e-1, 'weight_decay': 1e-3, 'use_gc': True}, 10),
    ('adamp', {'lr': 5e-1, 'weight_decay': 1e-3, 'nesterov': True}, 5),
    ('diffgrad', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('diffgrad', {'lr': 5e-1, 'weight_decay': 1e-3, 'ams_bound': True}, 5),
    ('diffgrad', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('diffgrad', {'lr': 5e-1, 'weight_decay': 1e-3, 'rectify': True}, 5),
    ('dualadam', {'lr': 5e-1, 'weight_decay': 1e-3, 'switch_rate': 0.25}, 5),
    ('lamb', {'lr': 1e-1, 'weight_decay': 1e-3}, 5),
    ('lamb', {'lr': 1e-1, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('lamb', {'lr': 1e-1, 'weight_decay': 1e-3, 'pre_norm': True, 'max_grad_norm': 0.0}, 5),
    ('lamb', {'lr': 5e-2, 'weight_decay': 1e-3, 'grad_averaging': False}, 5),
    ('lamb', {'lr': 5e-2, 'weight_decay': 1e-3, 'adam': True, 'eps': 1e-8}, 5),
    ('lamb', {'lr': 1e-1, 'weight_decay': 1e-3, 'pre_norm': True, 'eps': 1e-8}, 5),
    ('lamb', {'lr': 5e-1, 'weight_decay': 1e-3, 'rectify': True, 'degenerated_to_sgd': True}, 5),
    ('lars', {'lr': 5e-1, 'weight_decay': 1e-3}, 20),
    ('lars', {'lr': 5e-1, 'nesterov': True}, 20),
    ('madgrad', {'lr': 5e-1, 'weight_decay': 1e-3}, 10),
    ('madgrad', {'lr': 5e-1, 'weight_decay': 1e-3, 'eps': 0.0}, 10),
    ('madgrad', {'lr': 1e-1, 'weight_decay': 1e-3, 'momentum': 0.0}, 10),
    ('madgrad', {'lr': 1e-1, 'weight_decay': 1e-3, 'momentum': 0.0, 'eps': 0.0}, 10),
    ('madgrad', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': True}, 10),
    ('magma', {'lr': 5e-1, 'mask_prob': 1.0}, 5),
    ('radam', {'lr': 5e0, 'weight_decay': 1e-3}, 10),
    ('radam', {'lr': 5e-1, 'weight_decay': 1e-3, 'degenerated_to_sgd': True}, 5),
    ('sgdp', {'lr': 5e-1, 'weight_decay': 1e-4}, 10),
    ('sgdp', {'lr': 5e-1, 'weight_decay': 1e-4, 'nesterov': True}, 10),
    ('ranger', {'lr': 1e0, 'weight_decay': 1e-3}, 75),
    ('ranger', {'lr': 5e0, 'weight_decay': 1e-3, 'degenerated_to_sgd': True}, 5),
    ('ranger21', {'lr': 7.5e-1, 'weight_decay': 1e-3, 'num_iterations': 75}, 75),
    ('shampoo', {'lr': 5e-1, 'weight_decay': 1e-3, 'momentum': 0.1}, 10),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 9,
            'graft_type': 0,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'graft_type': 1,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'graft_type': 2,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-2,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'graft_type': 3,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'graft_type': 4,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'pre_conditioner_type': 0,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'pre_conditioner_type': 1,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'pre_conditioner_type': 2,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'inverse_exponent_override': 1,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'nesterov': False,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'decoupled_weight_decay': True,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-0,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'decoupled_learning_rate': False,
        },
        10,
    ),
    (
        'scalableshampoo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'start_preconditioning_step': 9,
            'preconditioning_compute_steps': 10,
            'moving_average_for_momentum': True,
        },
        10,
    ),
    ('pnm', {'lr': 5e-1}, 25),
    ('pnm', {'lr': 5e-1, 'weight_decouple': False}, 25),
    ('adapnm', {'lr': 5e-1, 'weight_decay': 1e-3}, 10),
    ('adapnm', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': False}, 10),
    ('adapnm', {'lr': 5e-1, 'weight_decay': 1e-3, 'ams_bound': False}, 10),
    ('nero', {'lr': 5e-1}, 25),
    ('nero', {'lr': 5e0, 'constraints': False}, 5),
    ('adan', {'lr': 5e-1}, 5),
    ('adan', {'lr': 5e-1, 'max_grad_norm': 1.0}, 5),
    ('adan', {'lr': 5e-1, 'weight_decay': 1e-3, 'use_gc': True}, 5),
    ('adan', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': True}, 5),
    ('dadaptadagrad', {'lr': 3e0, 'weight_decay': 1e-3}, 30),
    ('dadaptadagrad', {'lr': 5e0, 'weight_decay': 1e-3, 'momentum': 0.1}, 20),
    ('dadaptadam', {'lr': 1e2, 'weight_decay': 1e-3}, 5),
    ('dadaptsgd', {'lr': 2e0, 'weight_decay': 1e-3}, 25),
    ('dadaptadan', {'lr': 2e0, 'weight_decay': 1e-3}, 20),
    ('dadaptadan', {'lr': 2e0, 'weight_decay': 1e-3, 'weight_decouple': True}, 20),
    ('dadaptlion', {'lr': 3e0, 'weight_decay': 1e-3}, 20),
    ('adams', {'lr': 1e0, 'weight_decay': 1e-3}, 10),
    ('adams', {'lr': 1e0, 'weight_decay': 1e-3, 'ams_bound': True, 'weight_decouple': False}, 20),
    ('adafactor', {'lr': 1e0, 'weight_decay': 1e-3, 'scale_parameter': False, 'relative_step': False}, 5),
    ('adafactor', {'lr': 1e0, 'weight_decay': 1e-3, 'ams_bound': True, 'relative_step': False}, 10),
    ('adafactor', {'lr': 5e-1, 'betas': (None, 0.999), 'weight_decay': 1e-3, 'scale_parameter': False}, 50),
    ('apollodqn', {'lr': 5e-1, 'weight_decay': 1e-3}, 10),
    ('apollodqn', {'lr': 5e-1, 'weight_decay': 1e-3, 'rebound': 'belief'}, 10),
    ('apollodqn', {'lr': 1e-2, 'weight_decay': 1e-6, 'weight_decay_type': 'stable', 'warmup_steps': 0}, 5),
    ('novograd', {'lr': 5e-1, 'weight_decay': 1e-3, 'grad_averaging': True, 'weight_decouple': True}, 10),
    ('lion', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('lion', {'lr': 5e-1, 'betas': (0.75, 0.5), 'weight_decay': 1e-3}, 5),
    ('lorarite', {'lr': 3e-2, 'betas': (0.9, 0.999), 'clip_unmagnified_grad': 1.0}, 10),
    ('lion', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('lion', {'lr': 5e-1, 'weight_decay': 1e-3, 'use_gc': True}, 10),
    ('alig', {'max_lr': 5e-1, 'momentum': 0.9}, 5),
    ('alig', {'max_lr': 5e-1, 'momentum': 0.9, 'adjusted_momentum': True}, 5),
    ('sm3', {'lr': 5e-1, 'momentum': 0.9, 'beta': 0.9}, 5),
    ('adanorm', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('adanorm', {'lr': 5e-1, 'weight_decay': 1e-3, 'fixed_decay': True}, 5),
    ('adanorm', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('adanorm', {'lr': 5e-1, 'weight_decay': 1e-3, 'ams_bound': True}, 5),
    ('a2grad', {'variant': 'uni', 'beta': 1.0, 'lips': 1.0}, 5),
    ('a2grad', {'variant': 'inc', 'beta': 1.0, 'lips': 1.0}, 5),
    ('a2grad', {'variant': 'exp', 'beta': 1.0, 'lips': 1.0, 'rho': 0.9}, 5),
    ('accsgd', {'lr': 1e-0, 'weight_decay': 1e-3}, 5),
    ('sgdw', {'lr': 5e-1, 'momentum': 0.9, 'weight_decay': 1e-3}, 5),
    ('sgdw', {'lr': 5e-1, 'momentum': 0.9, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('sgdw', {'lr': 5e-1, 'momentum': 0.9, 'weight_decay': 1e-3, 'nesterov': True}, 5),
    ('asgd', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('asgd', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('yogi', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('fromage', {'lr': 5e-1, 'p_bound': 2.0}, 5),
    ('msvag', {'lr': 5e-1}, 10),
    ('adamod', {'lr': 5e1, 'weight_decay': 1e-3}, 10),
    ('adamod', {'lr': 5e1, 'weight_decay': 1e-3, 'weight_decouple': False}, 10),
    ('aggmo', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('aggmo', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': True}, 5),
    ('qhadam', {'lr': 1e0, 'nus': (0.9, 0.9), 'weight_decay': 1e-3}, 5),
    ('qhadam', {'lr': 1e0, 'weight_decay': 1e-3, 'weight_decouple': True}, 5),
    ('qhm', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('qhm', {'lr': 1e0, 'weight_decay': 1e-3, 'weight_decouple': True}, 5),
    ('pid', {'lr': 1e0, 'momentum': 0.9, 'dampening': 1.0, 'weight_decay': 1e-3}, 5),
    ('pid', {'lr': 1e0, 'momentum': 0.9, 'dampening': 1.0, 'weight_decay': 1e-3, 'weight_decouple': True}, 5),
    ('adamax', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('adamax', {'lr': 1e0, 'weight_decay': 1e-3, 'weight_decouple': True}, 5),
    ('adammini', {'lr': 5e-1, 'weight_decay': 1e-3, 'num_embeds': 2, 'num_heads': 1}, 5),
    ('gravity', {'lr': 1e0}, 5),
    ('adasmooth', {'lr': 1e-2}, 5),
    ('srmm', {'lr': 5e-1}, 5),
    ('avagrad', {'lr': 1e1}, 5),
    ('adashift', {'lr': 1e0, 'keep_num': 1}, 5),
    ('adadelta', {'lr': 5e1}, 5),
    ('amos', {'lr': 1e0, 'momentum': 0.9}, 5),
    ('signsgd', {'lr': 1e0, 'momentum': 0.0}, 5),
    ('signsgd', {'lr': 1e0, 'momentum': 0.9}, 5),
    ('sophiah', {'lr': 1e1, 'weight_decay': 1e-3, 'update_period': 2, 'hessian_distribution': 'gaussian'}, 5),
    ('adahessian', {'lr': 1e0, 'weight_decay': 1e-3, 'hessian_distribution': 'rademacher'}, 5),
    ('adahessian', {'lr': 1e0, 'weight_decay': 1e-3, 'hessian_distribution': 'gaussian'}, 5),
    ('swats', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('swats', {'lr': 5e-1, 'weight_decay': 1e-3, 'ams_bound': True}, 5),
    ('prodigy', {'lr': 5e1, 'beta3': None, 'weight_decay': 1e-3}, 10),
    ('prodigy', {'lr': 5e0, 'beta3': None, 'weight_decay': 1e-3, 'eps': None}, 15),
    ('prodigy', {'lr': 5e1, 'beta3': 0.999, 'weight_decay': 1e-3}, 10),
    ('prodigy', {'lr': 1e1, 'beta3': 0.999, 'weight_decay': 1e-3, 'bias_correction': True}, 15),
    ('prodigy', {'lr': 1e0, 'beta3': 0.999, 'weight_decay': 1e-3, 'safeguard_warmup': True}, 15),
    ('padam', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('tiger', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('came', {'lr': 7.5e-1, 'weight_decay': 1e-3}, 70),
    ('came', {'lr': 7.5e-1, 'weight_decay': 1e-3, 'ams_bound': True}, 70),
    ('aida', {'lr': 1e0, 'weight_decay': 1e-3, 'ams_bound': True}, 5),
    (
        'galore',
        {'lr': 1e0, 'weight_decay': 1e-3, 'rank': 2, 'scale': 1.0, 'update_proj_gap': 1, 'projection_type': 'std'},
        5,
    ),
    (
        'galore',
        {
            'lr': 1e0,
            'weight_decay': 1e-3,
            'rank': 2,
            'scale': 1.0,
            'update_proj_gap': 1,
            'projection_type': 'reverse_std',
        },
        5,
    ),
    (
        'galore',
        {'lr': 5e-1, 'weight_decay': 1e-3, 'rank': 2, 'scale': 1.0, 'update_proj_gap': 2, 'projection_type': 'left'},
        5,
    ),
    (
        'galore',
        {'lr': 1e0, 'weight_decay': 1e-3, 'rank': 2, 'scale': 1.0, 'update_proj_gap': 1, 'projection_type': 'right'},
        5,
    ),
    (
        'galore',
        {'lr': 5e-1, 'weight_decay': 1e-3, 'rank': 2, 'scale': 1.0, 'update_proj_gap': 2, 'projection_type': 'full'},
        5,
    ),
    (
        'galore',
        {'lr': 1e0, 'weight_decay': 1e-3, 'rank': 2, 'scale': 1.0, 'update_proj_gap': 1, 'projection_type': 'random'},
        5,
    ),
    (
        'fira',
        {'lr': 5e-1, 'weight_decay': 1e-3, 'rank': 2, 'scale': 1.0, 'update_proj_gap': 2, 'projection_type': 'full'},
        5,
    ),
    ('adalite', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('schedulefreesgd', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('schedulefreeadamw', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('schedulefreeadamw', {'lr': 1e0, 'weight_decay': 1e-3, 'decoupling_c': 200}, 5),
    ('schedulefreeradam', {'lr': 1e2, 'weight_decay': 1e-3}, 20),
    ('fadam', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('flashadamw', {'lr': 5e-1, 'weight_decay': 1e-3, 'quantize': False}, 5),
    ('grokfastadamw', {'lr': 5e0, 'weight_decay': 1e-3, 'grokfast_after_step': 1}, 5),
    ('kate', {'lr': 5e-2}, 10),
    ('stableadamw', {'lr': 1e0}, 5),
    ('stableadamw', {'lr': 1e0, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    ('adamg', {'lr': 1e0, 'p': 0.5}, 60),
    ('ademamix', {'lr': 1e0}, 3),
    ('ademamix', {'lr': 1e0, 't_alpha_beta3': 5}, 3),
    ('ademamix', {'lr': 1e0, 'weight_decay': 1e-3, 'weight_decouple': True, 'fixed_decay': True}, 3),
    ('ademamix', {'lr': 5e-1, 'cautious': True, 'stable_adamw': True, 'weight_decay': 1e-3}, 15),
    ('simplifiedademamix', {'lr': 1e0}, 3),
    ('simplifiedademamix', {'lr': 1e0, 'beta1_warmup': 2, 'weight_decay': 1e-3}, 3),
    ('simplifiedademamix', {'lr': 1e-1, 'alpha': 0.5, 'weight_decay': 1e-3, 'weight_decouple': False}, 5),
    (
        'soap',
        {'lr': 1e0, 'shampoo_beta': 0.95, 'precondition_frequency': 1, 'merge_dims': False, 'precondition_1d': True},
        5,
    ),
    ('adopt', {'lr': 1e0}, 5),
    ('ftrl', {'lr': 1e0, 'beta': 0.0, 'lambda_1': 0.0, 'lambda_2': 0.0}, 5),
    ('muon', {'lr': 5e-1, 'weight_decay': 1e-3, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2, 'nesterov': True}, 5),
    ('muon', {'lr': 5e-1, 'weight_decay': 1e-3, 'use_adjusted_lr': True, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2}, 5),
    ('adamuon', {'lr': 5e-1, 'weight_decay': 1e-3, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2}, 5),
    ('adamuon', {'lr': 5e-1, 'weight_decay': 1e-3, 'use_adjusted_lr': True, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2}, 5),
    ('normuon', {'lr': 5e-1, 'weight_decay': 1e-3, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2, 'nesterov': True}, 5),
    (
        'normuon',
        {'lr': 5e-1, 'weight_decay': 1e-3, 'update_scale': 'match_rms', 'adamw_lr': 5e-1, 'adamw_wd': 1e-2},
        5,
    ),
    ('normuon', {'lr': 5e-1, 'weight_decay': 1e-3, 'use_adjusted_lr': True, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2}, 5),
    ('normuon', {'lr': 5e-1, 'weight_decay': 0.0, 'nesterov': False, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2}, 5),
    ('adago', {'lr': 5e-1, 'adamw_lr': 5e-1, 'adamw_wd': 1e-2, 'nesterov': True}, 5),
    ('laprop', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('laprop', {'lr': 1e0, 'centered': True, 'weight_decay': 1e-3}, 11),
    ('laprop', {'lr': 1e0, 'ams_bound': True, 'weight_decay': 1e-3}, 5),
    (
        'apollo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'rank': 2,
            'update_proj_gap': 1,
            'scale': 1.0,
            'scale_type': 'tensor',
            'projection_type': 'right',
        },
        15,
    ),
    (
        'apollo',
        {
            'lr': 1e-1,
            'weight_decay': 1e-3,
            'rank': 2,
            'update_proj_gap': 1,
            'scale': 1.0,
            'scale_type': 'channel',
            'projection_type': 'right',
        },
        15,
    ),
    ('mars', {'lr': 5e-1, 'lr_1d': 5e-1, 'weight_decay': 1e-3, 'mars_type': 'adamw'}, 5),
    ('mars', {'lr': 1e-1, 'weight_decay': 1e-3, 'mars_type': 'lion', 'optimize_1d': True}, 5),
    ('mars', {'lr': 5e-1, 'lr_1d': 5e-1, 'weight_decay': 1e-3, 'mars_type': 'shampoo'}, 5),
    ('mars', {'lr': 5e-1, 'lr_1d': 5e-1, 'weight_decay': 1e-3, 'mars_type': 'adamw', 'ams_bound': True}, 5),
    ('sgdsai', {'lr': 1e0}, 15),
    ('sgdsai', {'lr': 1e0, 'momentum': 0.0}, 15),
    ('grams', {'lr': 5e-2, 'weight_decay': 1e-3}, 10),
    ('spam', {'lr': 1e0, 'weight_decay': 1e-3, 'warmup_epoch': 1, 'grad_accu_steps': 1, 'update_proj_gap': 1}, 5),
    ('sara', {'lr': 5e-1, 'threshold': 1e3}, 5),
    ('sara', {'lr': 5e-1, 'threshold': 1e3, 'progressive_iter': 2, 'ams_bound': True, 'lambda_rank': 5e-4}, 5),
    ('stablespam', {'lr': 1e0, 'weight_decay': 1e-3, 'update_proj_gap': 1, 't_max': 5}, 5),
    ('tam', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('adatam', {'lr': 1e-1, 'weight_decay': 1e-3}, 5),
    ('focus', {'lr': 1e-1, 'weight_decay': 1e-3}, 5),
    ('kron', {'lr': 1e0, 'weight_decay': 1e-3}, 3),
    ('exadam', {'lr': 1e-1, 'weight_decay': 1e-3}, 5),
    ('scion', {'lr': 5e-1, 'constraint': False, 'weight_decay': 1e-3}, 5),
    ('scion', {'lr': 5e-1, 'constraint': True}, 20),
    ('scionlight', {'lr': 5e-1, 'constraint': False, 'weight_decay': 1e-3}, 5),
    ('scionlight', {'lr': 2e-1, 'constraint': True}, 5),
    ('adagc', {'lr': 1e-1, 'warmup_steps': 2, 'weight_decay': 1e-3}, 5),
    ('racs', {'lr': 1e0}, 5),
    ('alice', {'lr': 1e0, 'rank': 2, 'leading_basis': 1, 'update_interval': 2}, 5),
    ('vsgd', {'lr': 1e0}, 5),
    ('adamwsn', {'lr': 1e0}, 5),
    ('adamc', {'lr': 1e0}, 5),
    ('adamc', {'lr': 1e0, 'ams_bound': True}, 5),
    ('splus', {'lr': 5e-1, 'weight_decay': 1e-3, 'nonstandard_constant': 1e-1, 'inverse_steps': 2}, 5),
    (
        'splus',
        {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': False, 'nonstandard_constant': 1e-1, 'inverse_steps': 2},
        5,
    ),
    ('emonavi', {'lr': 1e-1, 'use_shadow': True}, 5),
    ('emolynx', {'lr': 5e-1, 'use_shadow': True}, 5),
    ('emofact', {'lr': 1e-1, 'use_shadow': True}, 5),
    ('ranger25', {'lr': 2.5e-2}, 10),
    ('ranger25', {'lr': 2.5e-2, 't_alpha_beta3': 5}, 10),
    ('ranger25', {'lr': 1e-2, 'stable_adamw': False}, 10),
    ('ranger25', {'lr': 5e-2, 'stable_adamw': False, 'orthograd': False, 'eps': None, 'lookahead_merge_time': 2}, 3),
    ('conda', {'lr': 1e0, 'weight_decay': 1e-3, 'scale': 1.0, 'update_proj_gap': 1, 'projection_type': 'std'}, 5),
    ('bcos', {'lr': 1e0, 'mode': 'm'}, 5),
    ('bcos', {'lr': 1e0, 'mode': 'g'}, 5),
    ('bcos', {'lr': 1e0, 'mode': 'c'}, 5),
    ('bcos', {'lr': 1e0, 'mode': 'c', 'simple_cond': True}, 5),
    ('ano', {'lr': 1e0, 'weight_decay': 1e-3, 'logarithmic_schedule': True}, 5),
    ('spectralsphere', {'lr': 5e-1, 'momentum': 0.95, 'weight_decay': 1e-3, 'msign_steps': 8}, 5),
    ('rose', {'lr': 1e0, 'weight_decay': 1e-3}, 5),
    ('rose', {'lr': 1e0, 'weight_decay': 1e-3, 'wd_schedule': 1e0}, 5),
    ('rose', {'lr': 7.5e-1, 'weight_decay': 1e-3, 'stabilize': False}, 10),
    ('dualadam', {'lr': 1e0, 'weight_decay': 1e-3, 'weight_decouple': True, 'switch_rate': 0.5}, 5),
    ('lorarite', {'lr': 5e-1, 'weight_decay': 1e-3, 'weight_decouple': True, 'update_capping': 0.1}, 5),
    ('flashadamw', {'lr': 5e-1, 'weight_decay': 1e-3, 'check_numerics': True, 'master_weight_bits': None}, 5),
]

COMPILE_SUPPORTED_OPTIMIZERS: list[tuple[str, dict[str, Any], int]] = [
    ('lion', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('adamw', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
    ('stableadamw', {'lr': 5e-1, 'weight_decay': 1e-3}, 5),
]
