from typing import Callable, Dict, Optional, Set, Tuple, Union

import torch
from torch import Tensor
from torch.optim import AdamW, Optimizer

from pytorch_optimizer.base.optimizer import BaseOptimizer
from pytorch_optimizer.base.type import (
    Closure,
    Defaults,
    Loss,
    OptimizerInstanceOrClass,
    ParamGroup,
    ParamsT,
    State,
)

_MOMENT_KEYS = ('exp_avg', 'momentum_buffer')


class Magma(BaseOptimizer):
    """Momentum-aligned gradient masking wrapper for PyTorch optimizers.

    Magma applies a block-wise Bernoulli mask to the updates generated by a
    base optimizer. Surviving updates are scaled by an exponential moving
    average of the cosine similarity between the current gradient and the
    first-moment estimate. The base optimizer's state is updated densely,
    including when a parameter update is masked.

    Args:
        optimizer (OptimizerInstanceOrClass or ParamsT): Base optimizer instance/class,
            or parameters to optimize with AdamW.
        mask_prob (float): Probability of keeping an update.
        tau (float): Temperature used by the alignment sigmoid.
        momentum_beta (float): EMA coefficient for the fallback momentum.
        alignment_ema (float): EMA coefficient for the alignment score.
        moment_key (Optional[str]): First-moment key in the base optimizer's
            state. ``'auto'`` checks ``'exp_avg'`` and ``'momentum_buffer'``;
            ``None`` always uses Magma's fallback momentum.
        exclude (Optional[Set[Tensor]]): Parameters that bypass masking.

    Magma reads the first moment from the base optimizer when it is available,
    so it adds no additional momentum state for optimizers such as Adam. For
    optimizers without a first-moment buffer, it maintains an EMA controlled
    by ``momentum_beta``.

    Reference:
        https://arxiv.org/abs/2602.15322

    """

    def __init__(
        self,
        optimizer: Union[OptimizerInstanceOrClass, ParamsT],
        mask_prob: float = 0.5,
        tau: float = 2.0,
        momentum_beta: float = 0.9,
        alignment_ema: float = 0.9,
        moment_key: Optional[str] = 'auto',
        exclude: Optional[Set[Tensor]] = None,
        **kwargs,
    ) -> None:
        self.validate_range(mask_prob, 'mask_prob', 0.0, 1.0, range_type='[]')
        self.validate_positive(tau, 'tau')
        self.validate_range(momentum_beta, 'momentum_beta', 0.0, 1.0, range_type='[]')
        self.validate_range(alignment_ema, 'alignment_ema', 0.0, 1.0, range_type='[]')

        self._optimizer_step_pre_hooks: Dict[int, Callable] = {}
        self._optimizer_step_post_hooks: Dict[int, Callable] = {}

        if isinstance(optimizer, Optimizer):
            self.optimizer = optimizer
        elif isinstance(optimizer, type) and issubclass(optimizer, Optimizer):
            self.optimizer = self.load_optimizer(optimizer, **kwargs)
        else:
            self.validate_learning_rate(kwargs.get('lr', 1e-3))
            kwargs.pop('num_iterations', None)
            self.optimizer = self.load_optimizer(AdamW, params=optimizer, **kwargs)

        self.mask_prob = mask_prob
        self.tau = tau
        self.momentum_beta = momentum_beta
        self.alignment_ema = alignment_ema
        self.moment_key = moment_key
        self._exclude_ids: Set[int] = {id(parameter) for parameter in (exclude or set())}
        self._state: Dict[int, Dict[str, Tensor]] = {}

        self.defaults: Defaults = self.optimizer.defaults

    def __str__(self) -> str:
        return 'Magma'

    @property
    def param_groups(self):
        return self.optimizer.param_groups

    @property
    def state(self) -> State:
        return self.optimizer.state

    def add_param_group(self, param_group: ParamGroup) -> None:
        self.optimizer.add_param_group(param_group)

    def state_dict(self) -> State:
        id_to_key: Dict[int, Tuple[int, int]] = {
            id(parameter): (group_index, parameter_index)
            for group_index, group in enumerate(self.param_groups)
            for parameter_index, parameter in enumerate(group['params'])
        }

        magma_state: Dict[Tuple[int, int], Dict[str, Tensor]] = {}
        for parameter_id, parameter_state in self._state.items():
            key = id_to_key.get(parameter_id)
            if key is not None:
                magma_state[key] = {name: value.clone() for name, value in parameter_state.items()}

        return {
            'base': self.optimizer.state_dict(),
            'magma_state': magma_state,
            'mask_prob': self.mask_prob,
            'tau': self.tau,
            'momentum_beta': self.momentum_beta,
            'alignment_ema': self.alignment_ema,
            'moment_key': self.moment_key,
        }

    def load_state_dict(self, state_dict: State) -> None:
        base_state = state_dict.get('base', state_dict.get('base_optimizer'))
        if base_state is None:
            raise KeyError("state_dict must contain 'base'")

        self.optimizer.load_state_dict(base_state)

        self.mask_prob = state_dict['mask_prob']
        self.tau = state_dict['tau']
        self.momentum_beta = state_dict['momentum_beta']
        self.alignment_ema = state_dict['alignment_ema']
        if 'moment_key' in state_dict:
            self.moment_key = state_dict['moment_key']

        key_to_id: Dict[Tuple[int, int], int] = {
            (group_index, parameter_index): id(parameter)
            for group_index, group in enumerate(self.param_groups)
            for parameter_index, parameter in enumerate(group['params'])
        }

        self._state = {}
        for key, parameter_state in state_dict.get('magma_state', {}).items():
            normalized_key = tuple(key) if isinstance(key, list) else key
            parameter_id = key_to_id.get(normalized_key)
            if parameter_id is not None:
                self._state[parameter_id] = {name: value.clone() for name, value in parameter_state.items()}

    def init_group(self, group: ParamGroup, **kwargs) -> None:
        if 'step' not in group:
            group['step'] = 0

    def _get_first_moment(self, parameter: Tensor) -> Optional[Tensor]:
        if self.moment_key is None:
            return None

        parameter_state = self.optimizer.state.get(parameter)
        if not parameter_state:
            return None

        if self.moment_key != 'auto':
            moment = parameter_state.get(self.moment_key)
            return moment if isinstance(moment, Tensor) else None

        for key in _MOMENT_KEYS:
            moment = parameter_state.get(key)
            if isinstance(moment, Tensor):
                return moment

        return None

    def _capture_gradients(self, gradients: Dict[int, Tensor]) -> None:
        for group in self.param_groups:
            for parameter in group['params']:
                if parameter.grad is not None and id(parameter) not in self._exclude_ids:
                    gradients[id(parameter)] = parameter.grad.detach().clone()

    @torch.no_grad()
    def step(self, closure: Closure = None) -> Loss:
        snapshots: Dict[int, Tuple[Tensor, Tensor]] = {}
        gradients: Dict[int, Tensor] = {}
        for group in self.param_groups:
            for parameter in group['params']:
                if id(parameter) in self._exclude_ids:
                    continue
                if closure is not None or parameter.grad is not None:
                    snapshots[id(parameter)] = (parameter, parameter.detach().clone())
                if parameter.grad is not None:
                    gradients[id(parameter)] = parameter.grad.detach().clone()

        if closure is not None:

            def magma_closure():
                loss = closure()
                self._capture_gradients(gradients)
                return loss

            loss = self.optimizer.step(magma_closure)
        else:
            loss = self.optimizer.step()

        for parameter_id, (parameter, snapshot) in snapshots.items():
            gradient = gradients.get(parameter_id)
            if gradient is None or gradient.is_sparse:
                continue

            if parameter_id not in self._state:
                self._state[parameter_id] = {'alignment': torch.tensor(1.0, device=parameter.device)}

            parameter_state = self._state[parameter_id]
            moment = self._get_first_moment(parameter)
            if moment is None:
                if 'momentum' not in parameter_state:
                    parameter_state['momentum'] = torch.zeros_like(parameter)
                parameter_state['momentum'].mul_(self.momentum_beta).add_(gradient, alpha=1.0 - self.momentum_beta)
                moment = parameter_state['momentum']

            cosine = torch.nn.functional.cosine_similarity(
                moment.flatten().unsqueeze(0), gradient.flatten().unsqueeze(0)
            ).item()
            alignment = torch.sigmoid(torch.tensor(cosine / self.tau, device=parameter.device)).item()
            previous_alignment = parameter_state['alignment'].item()
            alignment = self.alignment_ema * previous_alignment + (1.0 - self.alignment_ema) * alignment
            parameter_state['alignment'].fill_(alignment)

            mask = torch.bernoulli(torch.tensor(self.mask_prob)).item()
            blend = alignment * mask
            if blend == 0.0:
                parameter.copy_(snapshot)
            elif blend != 1.0:
                parameter.mul_(blend).add_(snapshot, alpha=1.0 - blend)

        return loss

    @torch.no_grad()
    def zero_grad(self, set_to_none: bool = True) -> None:
        self.optimizer.zero_grad(set_to_none=set_to_none)
