name: Copy README.md to docs/index.md

on:
  pull_request:
    paths:
      - README.md

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy README.md to docs/index.md
        run: cp README.md docs/index.md

      - name: Commit updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v6
        id: auto-commit-action
        with:
          commit_message: "[skip ci] docs: update index.md"
          file_pattern: docs/index.md
          commit_user_name: "pytorch_optimizer-actions[bot]"
          commit_user_email: "pytorch_optimizer-actions[bot]@users.noreply.github.com"
          push_options: "--force"
