name: Label PR

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled' }}
      - run: echo "Done adding labels"
